title: feniX-ML
description: Herramienta para transformar ediciones críticas de teatro del Siglo de Oro de DOCX a XML-TEI.
theme: just-the-docs

# URL de tu sitio (opcional, se puede ajustar cuando esté publicado)
url: https://prolopeuab.github.io
baseurl: "/feniX-ML"

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/icon.ico"

# Enlaces auxiliares en la barra superior
aux_links:
  Repo GitHub: https://github.com/prolopeuab/feniX-ML
  Prolope: https://prolope.uab.cat/
  Biblioteca Digital: https://prolope.uab.cat/biblioteca/
  Contacto: mailto:prolope@uab.cat

# Opcional: habilita la búsqueda
search_enabled: true

# Orden de navegación si decides usar `_pages/`
nav_sort: case_insensitive
